version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: maawf
      MYSQL_DATABASE: maawf_db
      MYSQL_USER: maawf
      MYSQL_PASSWORD: maawf
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
