apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      annotations:
        timestamp: "{{ .Values.timestamp }}"
      labels:
        app: {{ .Values.frontend.name }}
    spec: # Pod spec
      containers:
        - name: {{ .Values.frontend.name }}
          image: "{{ .Values.frontend.image.name }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: "Always"
          ports:
          - containerPort: 80
          env:
            - name: "API_DOMAIN"
              value: {{ .Values.backend.domain }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.frontend.name }}
