appName: maawf
namespace: default

backend:
  domain: api.maawf.tech
  name: maawf-backend
  jwt_secret: maawf
  port: 5000
  image:
    name: medazizkhayati/maaawf_backend
    tag: latest

db:
  host: maawf-db
  port: "3306"
  user: maawf_user
  password: maawf
  name: maawf

frontend:
  domain: maawf.tech
  name: maawf-frontend
  port: 3000
  image:
    name: medazizkhayati/maaawf_frontend
    tag: latest

jwt:
  secret: maawf
