name: Ci/CD Pipeline

env:
  DOCKER_COMPOSE_FILE: 'docker-compose-test.yml'
  IMAGE_NAME: 'maaawf_backend'
  TAG: ${{ github.sha }}
  REGION: 'eu-central-1'
  CLUSTER_NAME: 'maawf-cluster'
  APP_NAME: 'maawf-backend'

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

jobs:
  analyze:
    name: Analyze
    runs-on: 'ubuntu-latest'
    timeout-minutes: ${{ 120 }}
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript-typescript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"

  test:
    # skip if commit starts with ci: or infra:
    if: true && !startsWith(github.event.head_commit.message, 'infra:') && !startsWith(github.event.head_commit.message, 'docs:') && !startsWith(github.event.head_commit.message, 'ci:')
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Test Docker images
        run: |
          docker compose -f $DOCKER_COMPOSE_FILE pull
          docker compose -f $DOCKER_COMPOSE_FILE build

      - name: Run tests
        run: docker compose -f $DOCKER_COMPOSE_FILE up --abort-on-container-exit --exit-code-from test --attach test

  build-push:
    if: github.event_name != 'pull_request'
    name: Build and push Docker images
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    name: Trigger deployment
    needs: build-push
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ${{ github.repository_owner }}
          repo: maawf_backend
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file_name: deploy.yaml
          ref: ${{ github.ref }}
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
