name: Ci/CD CD Pipeline

env:
  DOCKER_COMPOSE_FILE: 'docker-compose-test.yml'
  IMAGE_NAME: 'maaawf_backend'
  TAG: ${{ github.sha }}
  REGION: 'eu-central-1'
  CLUSTER_NAME: 'maawf-cluster'
  APP_NAME: 'maawf-backend'

on:
  push:
    branches: ['dev', 'test']
  pull_request:
    branches: ['dev']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Test Docker images
        run: |
          docker compose -f $DOCKER_COMPOSE_FILE pull
          docker compose -f $DOCKER_COMPOSE_FILE build

      - name: Run tests
        run: docker compose -f $DOCKER_COMPOSE_FILE up --abort-on-container-exit --exit-code-from test --attach test

  build-push:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    needs: test

    steps:
      - if: github.event_name != 'pull_request' && github.ref == 'refs/heads/dev'
        uses: actions/checkout@v3

      - if: github.event_name != 'pull_request' && github.ref == 'refs/heads/dev'
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: github.event_name != 'pull_request' && github.ref == 'refs/heads/dev'
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    name: Deploy to AWS EKS
    runs-on: ubuntu-latest
    needs: build-push

    steps:
      - if: github.event_name != 'pull_request'
        uses: actions/checkout@v3

      - if: github.event_name != 'pull_request'
        name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - if: github.event_name != 'pull_request'
        name:
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} 

          if [ ${{ github.ref }} == 'refs/heads/test' ]
            helm upgrade --install ${{ env.APP_NAME }}-test .helm --values .helm/values.yaml --values .helm/values-test.yaml
          else
            helm upgrade --install ${{ env.APP_NAME }} .helm --values .helm/values.yaml
          fi
