name: Deploy to AWS EKS

env:
  REGION: 'eu-central-1'
  CLUSTER_NAME: 'maawf-cluster'
  APP_NAME: 'maawf-backend'

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to AWS EKS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Deploy to AWS EKS
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} 
          helm upgrade --install ${{ env.APP_NAME }} .helm --values .helm/values.yaml
